# CI for AWS CDK project based on AWS CodeBuild (https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html)
version: 0.2
    
phases:   
  install:
    runtime-versions:
      nodejs: 12
      
  pre_build:
    commands:
      - npm install -g aws-cdk
      - cdk doctor
      - npm install
      
  build:
    commands:
      - npm run build
      - npx jest
      
  post_build:
    commands:
      - echo Build started on `diff`
      - |
        for envName in $(echo $ENV_NAMES | tr "," "\n")
        do
          echo $envName
          cdk diff "*-$envName"
        done